// Sample sales pipeline data for an Indian IT services company
// (Cloud Migration, Cybersecurity, SaaS Subscriptions, Managed Services, AI Implementation).
// Generated as internally-consistent fictional sample data. "Today" is treated as 2026-10-03.

export type Stage = "Lead" | "Qualified" | "Proposal" | "Negotiation" | "Closed Won";
export type ProductLine =
  | "Cloud Migration"
  | "Cybersecurity"
  | "SaaS Subscriptions"
  | "Managed Services"
  | "AI Implementation";
export type Region = "Mumbai" | "Delhi NCR" | "Bengaluru" | "Chennai";

export interface Deal {
  id: string;
  name: string;
  client: string;
  value: number;
  stage: Stage;
  productLine: ProductLine;
  region: Region;
  owner: string;
  probability: number;
  expectedCloseDate: string;
  createdDate: string;
  lastUpdated: string;
  nextAction: string;
  atRisk: boolean;
}

export interface SalesRep {
  id: string;
  name: string;
  avatarInitials: string;
  region: Region;
  dealsWon: number;
  dealsLost: number;
  totalClosedValue: number;
  quota: number;
  winRate: number;
}

export interface ForecastPoint {
  month: string;
  target: number;
  committed: number;
  projected: number;
}

export const STAGES: Stage[] = ["Lead", "Qualified", "Proposal", "Negotiation", "Closed Won"];

export const PRODUCT_LINES: ProductLine[] = [
  "Cloud Migration",
  "Cybersecurity",
  "SaaS Subscriptions",
  "Managed Services",
  "AI Implementation",
];

export const REGIONS: Region[] = ["Mumbai", "Delhi NCR", "Bengaluru", "Chennai"];

export const deals: Deal[] = [
  // ---- Lead (14) ----
  {
    id: "deal-01",
    name: "Cloud Migration — Konkan Shipping Ltd.",
    client: "Konkan Shipping Ltd.",
    value: 185000,
    stage: "Lead",
    productLine: "Cloud Migration",
    region: "Mumbai",
    owner: "Rohan Deshmukh",
    probability: 15,
    expectedCloseDate: "2027-01-20",
    createdDate: "2026-08-10",
    lastUpdated: "2026-09-30",
    nextAction: "Schedule technical discovery call with IT infra team",
    atRisk: false,
  },
  {
    id: "deal-02",
    name: "Cybersecurity — Himalaya Multispecialty Hospitals",
    client: "Himalaya Multispecialty Hospitals",
    value: 95000,
    stage: "Lead",
    productLine: "Cybersecurity",
    region: "Mumbai",
    owner: "Priya Nair",
    probability: 15,
    expectedCloseDate: "2026-12-15",
    createdDate: "2026-07-20",
    lastUpdated: "2026-09-22",
    nextAction: "Re-engage CISO after no response since last demo",
    atRisk: true,
  },
  {
    id: "deal-03",
    name: "SaaS Subscriptions — Suryodaya NBFC Ltd.",
    client: "Suryodaya NBFC Ltd.",
    value: 42000,
    stage: "Lead",
    productLine: "SaaS Subscriptions",
    region: "Mumbai",
    owner: "Karan Mehta",
    probability: 10,
    expectedCloseDate: "2026-11-28",
    createdDate: "2026-08-25",
    lastUpdated: "2026-10-01",
    nextAction: "Send pricing tiers for compliance module",
    atRisk: false,
  },
  {
    id: "deal-04",
    name: "Managed Services — Rangoli Lifestyle Retail",
    client: "Rangoli Lifestyle Retail",
    value: 68000,
    stage: "Lead",
    productLine: "Managed Services",
    region: "Delhi NCR",
    owner: "Ananya Banerjee",
    probability: 20,
    expectedCloseDate: "2026-11-05",
    createdDate: "2026-07-15",
    lastUpdated: "2026-09-29",
    nextAction: "Confirm stakeholders for SLA workshop",
    atRisk: false,
  },
  {
    id: "deal-05",
    name: "AI Implementation — Mahanadi Steel Works",
    client: "Mahanadi Steel Works",
    value: 310000,
    stage: "Lead",
    productLine: "AI Implementation",
    region: "Delhi NCR",
    owner: "Vikram Singh",
    probability: 15,
    expectedCloseDate: "2027-02-10",
    createdDate: "2026-08-15",
    lastUpdated: "2026-09-20",
    nextAction: "Follow up on stalled predictive-maintenance pilot proposal",
    atRisk: true,
  },
  {
    id: "deal-06",
    name: "Cloud Migration — Coromandel Logistics Pvt. Ltd.",
    client: "Coromandel Logistics Pvt. Ltd.",
    value: 220000,
    stage: "Lead",
    productLine: "Cloud Migration",
    region: "Bengaluru",
    owner: "Lakshmi Iyer",
    probability: 20,
    expectedCloseDate: "2026-12-01",
    createdDate: "2026-07-10",
    lastUpdated: "2026-10-02",
    nextAction: "Share migration cost-benefit assessment",
    atRisk: false,
  },
  {
    id: "deal-07",
    name: "Cybersecurity — Pune Municipal Smart City Corporation",
    client: "Pune Municipal Smart City Corporation",
    value: 135000,
    stage: "Lead",
    productLine: "Cybersecurity",
    region: "Bengaluru",
    owner: "Arjun Reddy",
    probability: 10,
    expectedCloseDate: "2027-01-30",
    createdDate: "2026-08-18",
    lastUpdated: "2026-09-28",
    nextAction: "Await security clearance from municipal IT cell",
    atRisk: false,
  },
  {
    id: "deal-08",
    name: "SaaS Subscriptions — Tarang Media Network",
    client: "Tarang Media Network",
    value: 36000,
    stage: "Lead",
    productLine: "SaaS Subscriptions",
    region: "Chennai",
    owner: "Meera Krishnan",
    probability: 15,
    expectedCloseDate: "2026-11-18",
    createdDate: "2026-08-01",
    lastUpdated: "2026-09-26",
    nextAction: "Demo content-management SaaS suite to editorial team",
    atRisk: false,
  },
  {
    id: "deal-09",
    name: "Managed Services — Gyanodaya University Trust",
    client: "Gyanodaya University Trust",
    value: 88000,
    stage: "Lead",
    productLine: "Managed Services",
    region: "Chennai",
    owner: "Suresh Pillai",
    probability: 10,
    expectedCloseDate: "2027-02-20",
    createdDate: "2026-08-28",
    lastUpdated: "2026-09-19",
    nextAction: "Chase unresponsive procurement office for NOC",
    atRisk: true,
  },
  {
    id: "deal-10",
    name: "AI Implementation — Sahyadri Energy Ltd.",
    client: "Sahyadri Energy Ltd.",
    value: 420000,
    stage: "Lead",
    productLine: "AI Implementation",
    region: "Mumbai",
    owner: "Rohan Deshmukh",
    probability: 15,
    expectedCloseDate: "2027-01-10",
    createdDate: "2026-07-25",
    lastUpdated: "2026-10-01",
    nextAction: "Present AI load-forecasting use case to ops head",
    atRisk: false,
  },
  {
    id: "deal-11",
    name: "Cloud Migration — Sindhu Communications Ltd.",
    client: "Sindhu Communications Ltd.",
    value: 265000,
    stage: "Lead",
    productLine: "Cloud Migration",
    region: "Mumbai",
    owner: "Priya Nair",
    probability: 20,
    expectedCloseDate: "2026-11-22",
    createdDate: "2026-06-28",
    lastUpdated: "2026-09-27",
    nextAction: "Validate data-residency requirements with legal",
    atRisk: false,
  },
  {
    id: "deal-12",
    name: "Cybersecurity — Sanjeevani Healthcare Group",
    client: "Sanjeevani Healthcare Group",
    value: 112000,
    stage: "Lead",
    productLine: "Cybersecurity",
    region: "Mumbai",
    owner: "Karan Mehta",
    probability: 15,
    expectedCloseDate: "2026-12-28",
    createdDate: "2026-08-14",
    lastUpdated: "2026-09-30",
    nextAction: "Share HIPAA-equivalent compliance brief",
    atRisk: false,
  },
  {
    id: "deal-13",
    name: "SaaS Subscriptions — Varun Trust Financial Services",
    client: "Varun Trust Financial Services",
    value: 29000,
    stage: "Lead",
    productLine: "SaaS Subscriptions",
    region: "Delhi NCR",
    owner: "Ananya Banerjee",
    probability: 10,
    expectedCloseDate: "2026-11-10",
    createdDate: "2026-08-02",
    lastUpdated: "2026-10-02",
    nextAction: "Set up trial account for finance team",
    atRisk: false,
  },
  {
    id: "deal-14",
    name: "Managed Services — Saffron Mart Supermarkets",
    client: "Saffron Mart Supermarkets",
    value: 75000,
    stage: "Lead",
    productLine: "Managed Services",
    region: "Delhi NCR",
    owner: "Vikram Singh",
    probability: 20,
    expectedCloseDate: "2026-12-05",
    createdDate: "2026-07-30",
    lastUpdated: "2026-09-29",
    nextAction: "Prepare SLA proposal walkthrough for ops head",
    atRisk: false,
  },

  // ---- Qualified (13) ----
  {
    id: "deal-15",
    name: "AI Implementation — Nirman Housing Finance",
    client: "Nirman Housing Finance",
    value: 380000,
    stage: "Qualified",
    productLine: "AI Implementation",
    region: "Bengaluru",
    owner: "Lakshmi Iyer",
    probability: 35,
    expectedCloseDate: "2026-12-12",
    createdDate: "2026-06-20",
    lastUpdated: "2026-10-01",
    nextAction: "Finalize AI credit-scoring pilot scope document",
    atRisk: false,
  },
  {
    id: "deal-16",
    name: "Cloud Migration — Vishal Fashion Hub",
    client: "Vishal Fashion Hub",
    value: 198000,
    stage: "Qualified",
    productLine: "Cloud Migration",
    region: "Bengaluru",
    owner: "Arjun Reddy",
    probability: 30,
    expectedCloseDate: "2026-11-25",
    createdDate: "2026-06-15",
    lastUpdated: "2026-09-25",
    nextAction: "Confirm data-center shortlist with client IT team",
    atRisk: false,
  },
  {
    id: "deal-17",
    name: "Cybersecurity — Deccan Alloys Pvt. Ltd.",
    client: "Deccan Alloys Pvt. Ltd.",
    value: 145000,
    stage: "Qualified",
    productLine: "Cybersecurity",
    region: "Chennai",
    owner: "Meera Krishnan",
    probability: 25,
    expectedCloseDate: "2027-01-15",
    createdDate: "2026-07-20",
    lastUpdated: "2026-09-19",
    nextAction: "Chase delayed sign-off on security audit scope",
    atRisk: true,
  },
  {
    id: "deal-18",
    name: "SaaS Subscriptions — Ganga Freight Carriers",
    client: "Ganga Freight Carriers",
    value: 54000,
    stage: "Qualified",
    productLine: "SaaS Subscriptions",
    region: "Chennai",
    owner: "Suresh Pillai",
    probability: 30,
    expectedCloseDate: "2026-11-30",
    createdDate: "2026-07-12",
    lastUpdated: "2026-09-30",
    nextAction: "Walk through fleet-tracking SaaS dashboard with ops lead",
    atRisk: false,
  },
  {
    id: "deal-19",
    name: "Managed Services — Sagar State Water Board",
    client: "Sagar State Water Board",
    value: 102000,
    stage: "Qualified",
    productLine: "Managed Services",
    region: "Mumbai",
    owner: "Rohan Deshmukh",
    probability: 35,
    expectedCloseDate: "2026-12-20",
    createdDate: "2026-06-25",
    lastUpdated: "2026-10-02",
    nextAction: "Submit revised SLA matrix for board review",
    atRisk: false,
  },
  {
    id: "deal-20",
    name: "AI Implementation — Lotus Print & Media Group",
    client: "Lotus Print & Media Group",
    value: 295000,
    stage: "Qualified",
    productLine: "AI Implementation",
    region: "Mumbai",
    owner: "Priya Nair",
    probability: 30,
    expectedCloseDate: "2027-01-25",
    createdDate: "2026-08-01",
    lastUpdated: "2026-09-28",
    nextAction: "Present AI content-tagging proof of concept results",
    atRisk: false,
  },
  {
    id: "deal-21",
    name: "Cloud Migration — Navodaya Learning Institutes",
    client: "Navodaya Learning Institutes",
    value: 162000,
    stage: "Qualified",
    productLine: "Cloud Migration",
    region: "Mumbai",
    owner: "Karan Mehta",
    probability: 25,
    expectedCloseDate: "2026-12-08",
    createdDate: "2026-06-15",
    lastUpdated: "2026-09-20",
    nextAction: "Follow up on frozen budget approval for campus migration",
    atRisk: true,
  },
  {
    id: "deal-22",
    name: "Cybersecurity — Kaveri Hydro Power",
    client: "Kaveri Hydro Power",
    value: 178000,
    stage: "Qualified",
    productLine: "Cybersecurity",
    region: "Delhi NCR",
    owner: "Ananya Banerjee",
    probability: 40,
    expectedCloseDate: "2026-11-15",
    createdDate: "2026-06-30",
    lastUpdated: "2026-09-29",
    nextAction: "Schedule red-team assessment kickoff",
    atRisk: false,
  },
  {
    id: "deal-23",
    name: "SaaS Subscriptions — Megh Broadband Networks",
    client: "Megh Broadband Networks",
    value: 47000,
    stage: "Qualified",
    productLine: "SaaS Subscriptions",
    region: "Delhi NCR",
    owner: "Vikram Singh",
    probability: 30,
    expectedCloseDate: "2026-12-02",
    createdDate: "2026-07-22",
    lastUpdated: "2026-10-01",
    nextAction: "Negotiate seat-count pricing with procurement",
    atRisk: false,
  },
  {
    id: "deal-24",
    name: "Managed Services — Lifeline Diagnostics Network",
    client: "Lifeline Diagnostics Network",
    value: 118000,
    stage: "Qualified",
    productLine: "Managed Services",
    region: "Bengaluru",
    owner: "Lakshmi Iyer",
    probability: 35,
    expectedCloseDate: "2026-11-28",
    createdDate: "2026-07-02",
    lastUpdated: "2026-09-26",
    nextAction: "Align on 24x7 support tier expectations",
    atRisk: false,
  },
  {
    id: "deal-25",
    name: "AI Implementation — Konkan Capital Finance",
    client: "Konkan Capital Finance",
    value: 410000,
    stage: "Qualified",
    productLine: "AI Implementation",
    region: "Bengaluru",
    owner: "Arjun Reddy",
    probability: 30,
    expectedCloseDate: "2027-01-18",
    createdDate: "2026-07-25",
    lastUpdated: "2026-09-23",
    nextAction: "Share fraud-detection model accuracy benchmarks",
    atRisk: false,
  },
  {
    id: "deal-26",
    name: "Cloud Migration — Spice Trail Retail Chain",
    client: "Spice Trail Retail Chain",
    value: 205000,
    stage: "Qualified",
    productLine: "Cloud Migration",
    region: "Chennai",
    owner: "Meera Krishnan",
    probability: 25,
    expectedCloseDate: "2026-12-18",
    createdDate: "2026-06-22",
    lastUpdated: "2026-09-21",
    nextAction: "Re-engage client after migration timeline questions went unanswered",
    atRisk: true,
  },
  {
    id: "deal-27",
    name: "Cybersecurity — Konkan Shipping Ltd.",
    client: "Konkan Shipping Ltd.",
    value: 88000,
    stage: "Qualified",
    productLine: "Cybersecurity",
    region: "Chennai",
    owner: "Suresh Pillai",
    probability: 35,
    expectedCloseDate: "2026-11-20",
    createdDate: "2026-07-14",
    lastUpdated: "2026-10-02",
    nextAction: "Finalize vulnerability-assessment statement of work",
    atRisk: false,
  },

  // ---- Proposal (9) ----
  {
    id: "deal-28",
    name: "SaaS Subscriptions — Himalaya Multispecialty Hospitals",
    client: "Himalaya Multispecialty Hospitals",
    value: 72000,
    stage: "Proposal",
    productLine: "SaaS Subscriptions",
    region: "Mumbai",
    owner: "Rohan Deshmukh",
    probability: 50,
    expectedCloseDate: "2026-11-12",
    createdDate: "2026-05-20",
    lastUpdated: "2026-10-01",
    nextAction: "Incorporate pricing feedback and resend proposal",
    atRisk: false,
  },
  {
    id: "deal-29",
    name: "Cloud Migration — Suryodaya NBFC Ltd.",
    client: "Suryodaya NBFC Ltd.",
    value: 340000,
    stage: "Proposal",
    productLine: "Cloud Migration",
    region: "Mumbai",
    owner: "Priya Nair",
    probability: 45,
    expectedCloseDate: "2026-12-02",
    createdDate: "2026-06-10",
    lastUpdated: "2026-09-22",
    nextAction: "Chase legal review of data-migration contract clauses",
    atRisk: true,
  },
  {
    id: "deal-30",
    name: "AI Implementation — Rangoli Lifestyle Retail",
    client: "Rangoli Lifestyle Retail",
    value: 455000,
    stage: "Proposal",
    productLine: "AI Implementation",
    region: "Mumbai",
    owner: "Karan Mehta",
    probability: 55,
    expectedCloseDate: "2026-11-28",
    createdDate: "2026-06-05",
    lastUpdated: "2026-09-30",
    nextAction: "Address CFO questions on AI implementation ROI model",
    atRisk: false,
  },
  {
    id: "deal-31",
    name: "Managed Services — Mahanadi Steel Works",
    client: "Mahanadi Steel Works",
    value: 190000,
    stage: "Proposal",
    productLine: "Managed Services",
    region: "Delhi NCR",
    owner: "Ananya Banerjee",
    probability: 50,
    expectedCloseDate: "2026-11-08",
    createdDate: "2026-05-25",
    lastUpdated: "2026-09-29",
    nextAction: "Finalize staffing plan for managed NOC services",
    atRisk: false,
  },
  {
    id: "deal-32",
    name: "Cybersecurity — Coromandel Logistics Pvt. Ltd.",
    client: "Coromandel Logistics Pvt. Ltd.",
    value: 160000,
    stage: "Proposal",
    productLine: "Cybersecurity",
    region: "Delhi NCR",
    owner: "Vikram Singh",
    probability: 60,
    expectedCloseDate: "2026-10-25",
    createdDate: "2026-05-05",
    lastUpdated: "2026-10-02",
    nextAction: "Confirm final pricing with CFO before contract draft",
    atRisk: false,
  },
  {
    id: "deal-33",
    name: "SaaS Subscriptions — Pune Municipal Smart City Corporation",
    client: "Pune Municipal Smart City Corporation",
    value: 58000,
    stage: "Proposal",
    productLine: "SaaS Subscriptions",
    region: "Bengaluru",
    owner: "Lakshmi Iyer",
    probability: 40,
    expectedCloseDate: "2026-12-10",
    createdDate: "2026-06-20",
    lastUpdated: "2026-09-20",
    nextAction: "Follow up on stalled municipal budget committee review",
    atRisk: true,
  },
  {
    id: "deal-34",
    name: "Cloud Migration — Tarang Media Network",
    client: "Tarang Media Network",
    value: 275000,
    stage: "Proposal",
    productLine: "Cloud Migration",
    region: "Bengaluru",
    owner: "Arjun Reddy",
    probability: 50,
    expectedCloseDate: "2026-11-15",
    createdDate: "2026-05-22",
    lastUpdated: "2026-09-27",
    nextAction: "Review revised infra sizing with client architects",
    atRisk: false,
  },
  {
    id: "deal-35",
    name: "AI Implementation — Gyanodaya University Trust",
    client: "Gyanodaya University Trust",
    value: 320000,
    stage: "Proposal",
    productLine: "AI Implementation",
    region: "Chennai",
    owner: "Meera Krishnan",
    probability: 45,
    expectedCloseDate: "2026-12-05",
    createdDate: "2026-06-12",
    lastUpdated: "2026-09-30",
    nextAction: "Present AI-based plagiarism detection pilot results to senate",
    atRisk: false,
  },
  {
    id: "deal-36",
    name: "Managed Services — Sahyadri Energy Ltd.",
    client: "Sahyadri Energy Ltd.",
    value: 215000,
    stage: "Proposal",
    productLine: "Managed Services",
    region: "Chennai",
    owner: "Suresh Pillai",
    probability: 55,
    expectedCloseDate: "2026-11-02",
    createdDate: "2026-05-12",
    lastUpdated: "2026-10-01",
    nextAction: "Confirm shift-coverage SLA terms with plant operations",
    atRisk: false,
  },

  // ---- Negotiation (7) ----
  {
    id: "deal-37",
    name: "Cloud Migration — Sindhu Communications Ltd.",
    client: "Sindhu Communications Ltd.",
    value: 480000,
    stage: "Negotiation",
    productLine: "Cloud Migration",
    region: "Mumbai",
    owner: "Rohan Deshmukh",
    probability: 75,
    expectedCloseDate: "2026-10-30",
    createdDate: "2026-05-10",
    lastUpdated: "2026-10-02",
    nextAction: "Finalize contract redlines with legal counsel",
    atRisk: false,
  },
  {
    id: "deal-38",
    name: "AI Implementation — Sanjeevani Healthcare Group",
    client: "Sanjeevani Healthcare Group",
    value: 610000,
    stage: "Negotiation",
    productLine: "AI Implementation",
    region: "Mumbai",
    owner: "Priya Nair",
    probability: 70,
    expectedCloseDate: "2026-11-10",
    createdDate: "2026-05-20",
    lastUpdated: "2026-09-21",
    nextAction: "Chase stalled approval from hospital board on final terms",
    atRisk: true,
  },
  {
    id: "deal-39",
    name: "Cybersecurity — Varun Trust Financial Services",
    client: "Varun Trust Financial Services",
    value: 210000,
    stage: "Negotiation",
    productLine: "Cybersecurity",
    region: "Delhi NCR",
    owner: "Ananya Banerjee",
    probability: 80,
    expectedCloseDate: "2026-10-20",
    createdDate: "2026-05-05",
    lastUpdated: "2026-10-02",
    nextAction: "Get CISO signature on final SOW",
    atRisk: false,
  },
  {
    id: "deal-40",
    name: "SaaS Subscriptions — Saffron Mart Supermarkets",
    client: "Saffron Mart Supermarkets",
    value: 85000,
    stage: "Negotiation",
    productLine: "SaaS Subscriptions",
    region: "Delhi NCR",
    owner: "Vikram Singh",
    probability: 65,
    expectedCloseDate: "2026-11-05",
    createdDate: "2026-05-12",
    lastUpdated: "2026-09-29",
    nextAction: "Negotiate multi-year discount tier with procurement",
    atRisk: false,
  },
  {
    id: "deal-41",
    name: "Managed Services — Nirman Housing Finance",
    client: "Nirman Housing Finance",
    value: 245000,
    stage: "Negotiation",
    productLine: "Managed Services",
    region: "Bengaluru",
    owner: "Lakshmi Iyer",
    probability: 85,
    expectedCloseDate: "2026-10-15",
    createdDate: "2026-05-01",
    lastUpdated: "2026-10-01",
    nextAction: "Route final MSA for e-signature",
    atRisk: false,
  },
  {
    id: "deal-42",
    name: "Cloud Migration — Vishal Fashion Hub",
    client: "Vishal Fashion Hub",
    value: 395000,
    stage: "Negotiation",
    productLine: "Cloud Migration",
    region: "Bengaluru",
    owner: "Arjun Reddy",
    probability: 70,
    expectedCloseDate: "2026-11-18",
    createdDate: "2026-05-25",
    lastUpdated: "2026-09-20",
    nextAction: "Resolve stalled data-sovereignty clause with client legal",
    atRisk: true,
  },
  {
    id: "deal-43",
    name: "AI Implementation — Deccan Alloys Pvt. Ltd.",
    client: "Deccan Alloys Pvt. Ltd.",
    value: 525000,
    stage: "Negotiation",
    productLine: "AI Implementation",
    region: "Chennai",
    owner: "Meera Krishnan",
    probability: 75,
    expectedCloseDate: "2026-10-28",
    createdDate: "2026-05-10",
    lastUpdated: "2026-10-02",
    nextAction: "Finalize phased payment milestones with CFO",
    atRisk: false,
  },

  // ---- Closed Won (5) ----
  {
    id: "deal-44",
    name: "Cloud Migration — Ganga Freight Carriers",
    client: "Ganga Freight Carriers",
    value: 420000,
    stage: "Closed Won",
    productLine: "Cloud Migration",
    region: "Chennai",
    owner: "Suresh Pillai",
    probability: 100,
    expectedCloseDate: "2026-09-18",
    createdDate: "2026-04-05",
    lastUpdated: "2026-09-19",
    nextAction: "Kick off post-migration support handover",
    atRisk: false,
  },
  {
    id: "deal-45",
    name: "Cybersecurity — Lifeline Diagnostics Network",
    client: "Lifeline Diagnostics Network",
    value: 175000,
    stage: "Closed Won",
    productLine: "Cybersecurity",
    region: "Bengaluru",
    owner: "Lakshmi Iyer",
    probability: 100,
    expectedCloseDate: "2026-09-25",
    createdDate: "2026-04-10",
    lastUpdated: "2026-09-26",
    nextAction: "Schedule quarterly security review cadence",
    atRisk: false,
  },
  {
    id: "deal-46",
    name: "AI Implementation — Konkan Capital Finance",
    client: "Konkan Capital Finance",
    value: 690000,
    stage: "Closed Won",
    productLine: "AI Implementation",
    region: "Bengaluru",
    owner: "Arjun Reddy",
    probability: 100,
    expectedCloseDate: "2026-09-30",
    createdDate: "2026-04-10",
    lastUpdated: "2026-10-01",
    nextAction: "Begin onboarding for AI model deployment phase 2",
    atRisk: false,
  },
  {
    id: "deal-47",
    name: "SaaS Subscriptions — Spice Trail Retail Chain",
    client: "Spice Trail Retail Chain",
    value: 63000,
    stage: "Closed Won",
    productLine: "SaaS Subscriptions",
    region: "Chennai",
    owner: "Meera Krishnan",
    probability: 100,
    expectedCloseDate: "2026-09-12",
    createdDate: "2026-04-02",
    lastUpdated: "2026-09-24",
    nextAction: "Confirm renewal date and upsell path",
    atRisk: false,
  },
  {
    id: "deal-48",
    name: "Managed Services — Konkan Shipping Ltd.",
    client: "Konkan Shipping Ltd.",
    value: 268000,
    stage: "Closed Won",
    productLine: "Managed Services",
    region: "Mumbai",
    owner: "Karan Mehta",
    probability: 100,
    expectedCloseDate: "2026-09-28",
    createdDate: "2026-04-10",
    lastUpdated: "2026-09-29",
    nextAction: "Transition account to managed services delivery team",
    atRisk: false,
  },
];

export const salesReps: SalesRep[] = [
  {
    id: "rep-01",
    name: "Rohan Deshmukh",
    avatarInitials: "RD",
    region: "Mumbai",
    dealsWon: 14,
    dealsLost: 6,
    totalClosedValue: 3150000,
    quota: 3000000,
    winRate: 70,
  },
  {
    id: "rep-02",
    name: "Priya Nair",
    avatarInitials: "PN",
    region: "Mumbai",
    dealsWon: 11,
    dealsLost: 9,
    totalClosedValue: 2480000,
    quota: 2600000,
    winRate: 55,
  },
  {
    id: "rep-03",
    name: "Karan Mehta",
    avatarInitials: "KM",
    region: "Mumbai",
    dealsWon: 9,
    dealsLost: 11,
    totalClosedValue: 2100000,
    quota: 2400000,
    winRate: 45,
  },
  {
    id: "rep-04",
    name: "Ananya Banerjee",
    avatarInitials: "AB",
    region: "Delhi NCR",
    dealsWon: 13,
    dealsLost: 5,
    totalClosedValue: 2900000,
    quota: 2800000,
    winRate: 72,
  },
  {
    id: "rep-05",
    name: "Vikram Singh",
    avatarInitials: "VS",
    region: "Delhi NCR",
    dealsWon: 10,
    dealsLost: 8,
    totalClosedValue: 2350000,
    quota: 2500000,
    winRate: 56,
  },
  {
    id: "rep-06",
    name: "Lakshmi Iyer",
    avatarInitials: "LI",
    region: "Bengaluru",
    dealsWon: 15,
    dealsLost: 5,
    totalClosedValue: 3400000,
    quota: 3200000,
    winRate: 75,
  },
  {
    id: "rep-07",
    name: "Arjun Reddy",
    avatarInitials: "AR",
    region: "Bengaluru",
    dealsWon: 9,
    dealsLost: 10,
    totalClosedValue: 2150000,
    quota: 2450000,
    winRate: 47,
  },
  {
    id: "rep-08",
    name: "Meera Krishnan",
    avatarInitials: "MK",
    region: "Chennai",
    dealsWon: 12,
    dealsLost: 6,
    totalClosedValue: 2750000,
    quota: 2700000,
    winRate: 67,
  },
  {
    id: "rep-09",
    name: "Suresh Pillai",
    avatarInitials: "SP",
    region: "Chennai",
    dealsWon: 10,
    dealsLost: 9,
    totalClosedValue: 2300000,
    quota: 2300000,
    winRate: 53,
  },
];

// 6 months of history (Apr–Sep 2026) + current month (Oct 2026) + 3 months forward (Nov 2026–Jan 2027).
export const forecastData: ForecastPoint[] = [
  { month: "Apr", target: 980000, committed: 940000, projected: 960000 },
  { month: "May", target: 1050000, committed: 1100000, projected: 1080000 },
  { month: "Jun", target: 1120000, committed: 1050000, projected: 1090000 },
  { month: "Jul", target: 1200000, committed: 1260000, projected: 1230000 },
  { month: "Aug", target: 1280000, committed: 1190000, projected: 1240000 },
  { month: "Sep", target: 1360000, committed: 1420000, projected: 1390000 },
  { month: "Oct", target: 1440000, committed: 1050000, projected: 1400000 },
  { month: "Nov", target: 1560000, committed: 760000, projected: 1500000 },
  { month: "Dec", target: 1700000, committed: 700000, projected: 1760000 },
  { month: "Jan", target: 1850000, committed: 700000, projected: 1900000 },
];
